<option value="#f0f8ff" style="color:#f0f8ff;">Alice Blue</option>
<option value="#faebd7" style="color:#faebd7;">Antique White</option>
<option value="#00ffff" style="color:#00ffff;">Aqua</option>
<option value="#7fffd4" style="color:#7fffd4;">Aquamarine</option>
<option value="#f0ffff" style="color:#f0ffff;">Azure</option>
<option value="#f5f5dc" style="color:#f5f5dc;">Beige</option>
<option value="#ffe4c4" style="color:#ffe4c4;">Bisque</option>
<option value="#000000" style="color:#000000;" selected>Black</option>
<option value="#ffebcd" style="color:#ffebcd;">Blanched Almond</option>
<option value="#0000ff" style="color:#0000ff;">Blue</option>
<option value="#8a2be2" style="color:#8a2be2;">Blue-Violet</option>
<option value="#a52a2a" style="color:#a52a2a;">Brown</option>
<option value="#deb887" style="color:#deb887;">Burlywood</option>
<option value="#5f9ea0" style="color:#5f9ea0;">Cadet Blue</option>
<option value="#7fff00" style="color:#7fff00;">Chartreuse</option>
<option value="#d2691e" style="color:#d2691e;">Chocolate</option>
<option value="#ff7f50" style="color:#ff7f50;">Coral</option>
<option value="#6495ed" style="color:#6495ed;">Cornflower Blue</option>
<option value="#fff8dc" style="color:#fff8dc;">Cornsilk</option>
<option value="#00ffff" style="color:#00ffff;">Cyan</option>
<option value="#00008b" style="color:#00008b;">Dark Blue</option>
<option value="#008b8b" style="color:#008b8b;">Dark Cyan</option>
<option value="#b8860b" style="color:#b8860b;">Dark Goldenrod</option>
<option value="#a9a9a9" style="color:#a9a9a9;">Dark Gray</option>
<option value="#006400" style="color:#006400;">Dark Green</option>
<option value="#bdb76b" style="color:#bdb76b;">Dark Khaki</option>
<option value="#8b008b" style="color:#8b008b;">Dark Magenta</option>
<option value="#556b2f" style="color:#556b2f;">Dark Olive Green</option>
<option value="#ff8c00" style="color:#ff8c00;">Dark Orange</option>
<option value="#9932cc" style="color:#9932cc;">Dark Orchid</option>
<option value="#8b0000" style="color:#8b0000;">Dark Red</option>
<option value="#e9967a" style="color:#e9967a;">Dark Salmon</option>
<option value="#8fbc8f" style="color:#8fbc8f;">Dark Sea Green</option>
<option value="#483d8b" style="color:#483d8b;">Dark Slate Blue</option>
<option value="#2f4f4f" style="color:#2f4f4f;">Dark Slate Gray</option>
<option value="#00ced1" style="color:#00ced1;">Dark Turquoise</option>
<option value="#9400d3" style="color:#9400d3;">Dark Violet</option>
<option value="#ff1493" style="color:#ff1493;">Deep Pink</option>
<option value="#00bfff" style="color:#00bfff;">Deep Sky Blue</option>
<option value="#696969" style="color:#696969;">Dim Gray</option>
<option value="#1e90ff" style="color:#1e90ff;">Dodger Blue</option>
<option value="#b22222" style="color:#b22222;">Firebrick</option>
<option value="#fffaf0" style="color:#fffaf0;">Floral White</option>
<option value="#228b22" style="color:#228b22;">Forest Green</option>
<option value="#ff00ff" style="color:#ff00ff;">Fuschia</option>
<option value="#dcdcdc" style="color:#dcdcdc;">Gainsboro</option>
<option value="#f8f8ff" style="color:#f8f8ff;">Ghost White</option>
<option value="#ffd700" style="color:#ffd700;">Gold</option>
<option value="#daa520" style="color:#daa520;">Goldenrod</option>
<option value="#808080" style="color:#808080;">Gray</option>
<option value="#008000" style="color:#008000;">Green</option>
<option value="#adff2f" style="color:#adff2f;">Green-Yellow</option>
<option value="#f0fff0" style="color:#f0fff0;">Honeydew</option>
<option value="#ff69b4" style="color:#ff69b4;">Hot Pink</option>
<option value="#cd5c5c" style="color:#cd5c5c;">Indian Red</option>
<option value="#fffff0" style="color:#fffff0;">Ivory</option>
<option value="#f0e68c" style="color:#f0e68c;">Khaki</option>
<option value="#e6e6fa" style="color:#e6e6fa;">Lavender</option>
<option value="#fff0f5" style="color:#fff0f5;">Lavender Blush</option>
<option value="#7cfc00" style="color:#7cfc00;">Lawn Green</option>
<option value="#fffacd" style="color:#fffacd;">Lemon Chiffon</option>
<option value="#add8e6" style="color:#add8e6;">Light Blue</option>
<option value="#f08080" style="color:#f08080;">Light Coral</option>
<option value="#e0ffff" style="color:#e0ffff;">Light Cyan</option>
<option value="#eedd82" style="color:#eedd82;">Light Goldenrod</option>
<option value="#fafad2" style="color:#fafad2;">Light Goldenrod Yellow</option>
<option value="#d3d3d3" style="color:#d3d3d3;">Light Gray</option>
<option value="#90ee90" style="color:#90ee90;">Light Green</option>
<option value="#ffb6c1" style="color:#ffb6c1;">Light Pink</option>
<option value="#ffa07a" style="color:#ffa07a;">Light Salmon</option>
<option value="#20b2aa" style="color:#20b2aa;">Light Sea Green</option>
<option value="#87cefa" style="color:#87cefa;">Light Sky Blue</option>
<option value="#8470ff" style="color:#8470ff;">Light Slate Blue</option>
<option value="#778899" style="color:#778899;">Light Slate Gray</option>
<option value="#b0c4de" style="color:#b0c4de;">Light Steel Blue</option>
<option value="#ffffe0" style="color:#ffffe0;">Light Yellow</option>
<option value="#00ff00" style="color:#00ff00;">Lime</option>
<option value="#32cd32" style="color:#32cd32;">Lime Green</option>
<option value="#faf0e6" style="color:#faf0e6;">Linen</option>
<option value="#ff00ff" style="color:#ff00ff;">Magenta</option>
<option value="#800000" style="color:#800000;">Maroon</option>
<option value="#66cdaa" style="color:#66cdaa;">Medium Aquamarine</option>
<option value="#0000cd" style="color:#0000cd;">Medium Blue</option>
<option value="#ba55d3" style="color:#ba55d3;">Medium Orchid</option>
<option value="#9370db" style="color:#9370db;">Medium Purple</option>
<option value="#3cb371" style="color:#3cb371;">Medium Sea Green</option>
<option value="#7b68ee" style="color:#7b68ee;">Medium Slate Blue</option>
<option value="#00fa9a" style="color:#00fa9a;">Medium Spring Green</option>
<option value="#48d1cc" style="color:#48d1cc;">Medium Turquoise</option>
<option value="#c71585" style="color:#c71585;">Medium Violet-Red</option>
<option value="#191970" style="color:#191970;">Midnight Blue</option>
<option value="#f5fffa" style="color:#f5fffa;">Mint Cream</option>
<option value="#e1e4e1" style="color:#e1e4e1;">Misty Rose</option>
<option value="#ffe4b5" style="color:#ffe4b5;">Moccasin</option>
<option value="#ffdead" style="color:#ffdead;">Navajo White</option>
<option value="#000080" style="color:#000080;">Navy</option>
<option value="#fdf5e6" style="color:#fdf5e6;">Old Lace</option>
<option value="#808000" style="color:#808000;">Olive</option>
<option value="#6b8e23" style="color:#6b8e23;">Olive Drab</option>
<option value="#ffa500" style="color:#ffa500;">Orange</option>
<option value="#ff4500" style="color:#ff4500;">Orange-Red</option>
<option value="#da70d6" style="color:#da70d6;">Orchid</option>
<option value="#eee8aa" style="color:#eee8aa;">Pale Goldenrod</option>
<option value="#98fb98" style="color:#98fb98;">Pale Green</option>
<option value="#afeeee" style="color:#afeeee;">Pale Turquoise</option>
<option value="#db7093" style="color:#db7093;">Pale Violet-Red</option>
<option value="#ffefd5" style="color:#ffefd5;">Papaya Whip</option>
<option value="#ffdab9" style="color:#ffdab9;">Peach Puff</option>
<option value="#cd853f" style="color:#cd853f;">Peru</option>
<option value="#ffc0cb" style="color:#ffc0cb;">Pink</option>
<option value="#dda0dd" style="color:#dda0dd;">Plum</option>
<option value="#b0e0e6" style="color:#b0e0e6;">Powder Blue</option>
<option value="#800080" style="color:#800080;">Purple</option>
<option value="#ff0000" style="color:#ff0000;">Red</option>
<option value="#bc8f8f" style="color:#bc8f8f;">Rosy Brown</option>
<option value="#4169e1" style="color:#4169e1;">Royal Blue</option>
<option value="#8b4513" style="color:#8b4513;">Saddle Brown</option>
<option value="#fa8072" style="color:#fa8072;">Salmon</option>
<option value="#f4a460" style="color:#f4a460;">Sandy Brown</option>
<option value="#2e8b57" style="color:#2e8b57;">Sea Green</option>
<option value="#fff5ee" style="color:#fff5ee;">Seashell</option>
<option value="#a0522d" style="color:#a0522d;">Sienna</option>
<option value="#c0c0c0" style="color:#c0c0c0;">Silver</option>
<option value="#87ceeb" style="color:#87ceeb;">Sky Blue</option>
<option value="#6a5acd" style="color:#6a5acd;">Slate Blue</option>
<option value="#708090" style="color:#708090;">Slate Gray</option>
<option value="#fffafa" style="color:#fffafa;">Snow</option>
<option value="#00ff7f" style="color:#00ff7f;">Spring Green</option>
<option value="#4682b4" style="color:#4682b4;">Steel Blue</option>
<option value="#d2b48c" style="color:#d2b48c;">Tan</option>
<option value="#008080" style="color:#008080;">Teal</option>
<option value="#d8bfd8" style="color:#d8bfd8;">Thistle</option>
<option value="#ff6347" style="color:#ff6347;">Tomato</option>
<option value="#40e0d0" style="color:#40e0d0;">Turquoise</option>
<option value="#ee82ee" style="color:#ee82ee;">Violet</option>
<option value="#d02090" style="color:#d02090;">Violet-Red</option>
<option value="#f5deb3" style="color:#f5deb3;">Wheat</option>
<option value="#ffffff" style="color:#ffffff;">White</option>
<option value="#f5f5f5" style="color:#f5f5f5;">White Smoke</option>
<option value="#ffff00" style="color:#ffff00;">Yellow</option>
<option value="#9acd32" style="color:#9acd32;">Yellow-Green</option>