/**
 * This class contains all the level data.
 */
function LevelMaps() {


  this.levels = [

    /* LEVEL 1 */
    [
      { background : "fire" },
      { x : 10, y : 0, type : "end" },
      { x : 10, y : 1, type : "bridge" },
      { x : 10, y : 10, type : "skull" },
      { x : 10, y : 11, type : "bridge" },
      { x : 10, y : 12, type : "bridge" },
      { x : 10, y : 13, type : "bridge" },
      { x : 10, y : 14, type : "bridge" },
      { x : 10, y : 2, type : "bridge" },
      { x : 10, y : 3, type : "skull" },
      { x : 10, y : 4, type : "bridge" },
      { x : 10, y : 5, type : "bridge" },
      { x : 10, y : 6, type : "bridge" },
      { x : 10, y : 7, type : "skull" },
      { x : 10, y : 9, type : "bridge" },
      { x : 11, y : 14, type : "bridge" },
      { x : 11, y : 19, type : "bridge" },
      { x : 11, y : 20, type : "bridge" },
      { x : 11, y : 21, type : "bridge" },
      { x : 11, y : 9, type : "bridge" },
      { x : 12, y : 13, type : "skull" },
      { x : 12, y : 14, type : "bridge" },
      { x : 12, y : 15, type : "bridge" },
      { x : 12, y : 16, type : "bridge" },
      { x : 12, y : 17, type : "bridge" },
      { x : 12, y : 18, type : "bridge" },
      { x : 12, y : 19, type : "bridge" },
      { x : 12, y : 20, type : "skull" },
      { x : 12, y : 21, type : "bridge" },
      { x : 12, y : 22, type : "bridge" },
      { x : 12, y : 23, type : "start" },
      { x : 12, y : 9, type : "bridge" },
      { x : 13, y : 0, type : "deadend" },
      { x : 13, y : 1, type : "bridge" },
      { x : 13, y : 14, type : "skull" },
      { x : 13, y : 19, type : "deadend" },
      { x : 13, y : 2, type : "bridge" },
      { x : 13, y : 20, type : "bridge" },
      { x : 13, y : 21, type : "bridge" },
      { x : 13, y : 3, type : "bridge" },
      { x : 13, y : 4, type : "bridge" },
      { x : 13, y : 5, type : "bridge" },
      { x : 13, y : 6, type : "bridge" },
      { x : 13, y : 7, type : "bridge" },
      { x : 13, y : 8, type : "bridge" },
      { x : 13, y : 9, type : "bridge" },
      { x : 14, y : 9, type : "rock" },
      { x : 8, y : 11, type : "bridge" },
      { x : 8, y : 12, type : "bridge" },
      { x : 8, y : 13, type : "bridge" },
      { x : 8, y : 9, type : "skull" },
      { x : 9, y : 0, type : "skull" },
      { x : 9, y : 1, type : "skull" },
      { x : 9, y : 10, type : "bridge" },
      { x : 9, y : 11, type : "bridge" },
      { x : 9, y : 12, type : "skull" },
      { x : 9, y : 13, type : "bridge" },
      { x : 9, y : 2, type : "bridge" },
      { x : 9, y : 3, type : "bridge" },
      { x : 9, y : 4, type : "bridge" },
      { x : 9, y : 5, type : "skull" },
      { x : 9, y : 6, type : "bridge" },
      { x : 9, y : 7, type : "bridge" },
      { x : 9, y : 8, type : "bridge" },
      { x : 9, y : 9, type : "bridge" }
    ],

    /* LEVEL 2 */
    [
      { background : "water" },
      { x : 10, y : 23, type : "start" },
      { x : 11, y : 23, type : "bridge" },
      { x : 12, y : 23, type : "bridge" },
      { x : 13, y : 23, type : "bridge" },
      { x : 13, y : 22, type : "bridge" },
      { x : 13, y : 21, type : "bridge" },
      { x : 13, y : 20, type : "skull" },
      { x : 14, y : 21, type : "bridge" },
      { x : 15, y : 21, type : "bridge" },
      { x : 16, y : 21, type : "rock" },
      { x : 16, y : 20, type : "deadend" },
      { x : 15, y : 20, type : "deadend" },
      { x : 14, y : 20, type : "bridge" },
      { x : 14, y : 19, type : "bridge" },
      { x : 13, y : 19, type : "bridge" },
      { x : 13, y : 18, type : "bridge" },
      { x : 13, y : 17, type : "bridge" },
      { x : 13, y : 16, type : "bridge" },
      { x : 14, y : 16, type : "skull" },
      { x : 14, y : 17, type : "bridge" },
      { x : 15, y : 17, type : "rock" },
      { x : 13, y : 15, type : "bridge" },
      { x : 13, y : 14, type : "skull" },
      { x : 12, y : 15, type : "bridge" },
      { x : 12, y : 14, type : "bridge" },
      { x : 12, y : 13, type : "bridge" },
      { x : 13, y : 13, type : "bridge" },
      { x : 14, y : 13, type : "bridge" },
      { x : 14, y : 14, type : "bridge" },
      { x : 14, y : 15, type : "bridge" },
      { x : 13, y : 12, type : "skull" },
      { x : 14, y : 12, type : "bridge" },
      { x : 12, y : 12, type : "bridge" },
      { x : 11, y : 12, type : "bridge" },
      { x : 10, y : 12, type : "bridge" },
      { x : 10, y : 11, type : "bridge" },
      { x : 11, y : 11, type : "rock" },
      { x : 12, y : 11, type : "bridge" },
      { x : 13, y : 11, type : "bridge" },
      { x : 14, y : 11, type : "bridge" },
      { x : 14, y : 10, type : "rock" },
      { x : 15, y : 10, type : "deadend" },
      { x : 15, y : 11, type : "bridge" },
      { x : 13, y : 10, type : "deadend" },
      { x : 12, y : 10, type : "deadend" },
      { x : 11, y : 10, type : "skull" },
      { x : 10, y : 10, type : "bridge" },
      { x : 9, y : 9, type : "rock" },
      { x : 10, y : 9, type : "bridge" },
      { x : 11, y : 9, type : "bridge" },
      { x : 12, y : 9, type : "bridge" },
      { x : 13, y : 9, type : "bridge" },
      { x : 14, y : 9, type : "rock" },
      { x : 10, y : 8, type : "rock" },
      { x : 11, y : 8, type : "deadend" },
      { x : 12, y : 8, type : "deadend" },
      { x : 13, y : 8, type : "skull" },
      { x : 14, y : 8, type : "skull" },
      { x : 15, y : 11, type : "bridge" },
      { x : 16, y : 11, type : "bridge" },
      { x : 17, y : 11, type : "bridge" },
      { x : 18, y : 11, type : "bridge" },
      { x : 19, y : 11, type : "bridge" },
      { x : 20, y : 11, type : "skull" },
      { x : 19, y : 12, type : "bridge" },
      { x : 19, y : 10, type : "skull" },
      { x : 20, y : 12, type : "bridge" },
      { x : 21, y : 12, type : "bridge" },
      { x : 21, y : 11, type : "bridge" },
      { x : 22, y : 12, type : "skull" },
      { x : 22, y : 11, type : "bridge" },
      { x : 23, y : 11, type : "bridge" },
      { x : 24, y : 11, type : "rock" },
      { x : 23, y : 10, type : "bridge" },
      { x : 24, y : 10, type : "bridge" },
      { x : 25, y : 10, type : "bridge" },
      { x : 26, y : 10, type : "bridge" },
      { x : 27, y : 10, type : "skull" },
      { x : 28, y : 10, type : "bridge" },
      { x : 23, y : 9, type : "bridge" },
      { x : 24, y : 9, type : "bridge" },
      { x : 25, y : 9, type : "skull" },
      { x : 26, y : 9, type : "bridge" },
      { x : 27, y : 9, type : "bridge" },
      { x : 28, y : 9, type : "bridge" },
      { x : 23, y : 8, type : "skull" },
      { x : 29, y : 10, type : "bridge" },
      { x : 30, y : 10, type : "bridge" },
      { x : 31, y : 10, type : "end" }
    ],

    /* LEVEL 3 */
    [
      { background : "air" },
      { x : 0, y : 12, type : "start" },
      { x : 1, y : 12, type : "bridge" },
      { x : 2, y : 12, type : "bridge" },
      { x : 3, y : 12, type : "bridge" },
      { x : 4, y : 12, type : "rock" },
      { x : 3, y : 11, type : "bridge" },
      { x : 4, y : 11, type : "bridge" },
      { x : 5, y : 12, type : "bridge" },
      { x : 5, y : 11, type : "bridge" },
      { x : 6, y : 12, type : "rock" },
      { x : 6, y : 11, type : "bridge" },
      { x : 6, y : 10, type : "bridge" },
      { x : 7, y : 10, type : "skull" },
      { x : 8, y : 10, type : "bridge" },
      { x : 6, y : 9, type : "rock" },
      { x : 7, y : 9, type : "bridge" },
      { x : 8, y : 9, type : "bridge" },
      { x : 7, y : 8, type : "bridge" },
      { x : 8, y : 8, type : "bridge" },
      { x : 9, y : 8, type : "bridge" },
      { x : 7, y : 7, type : "bridge" },
      { x : 8, y : 7, type : "skull" },
      { x : 9, y : 7, type : "bridge" },
      { x : 10, y : 7, type : "bridge" },
      { x : 11, y : 7, type : "bridge" },
      { x : 12, y : 7, type : "skull" },
      { x : 11, y : 6, type : "bridge" },
      { x : 11, y : 5, type : "bridge" },
      { x : 11, y : 4, type : "bridge" },
      { x : 12, y : 4, type : "bridge" },
      { x : 13, y : 4, type : "bridge" },
      { x : 14, y : 4, type : "skull" },
      { x : 13, y : 5, type : "bridge" },
      { x : 14, y : 5, type : "bridge" },
      { x : 15, y : 5, type : "bridge" },
      { x : 15, y : 4, type : "bridge" },
      { x : 16, y : 4, type : "bridge" },
      { x : 17, y : 4, type : "bridge" },
      { x : 17, y : 5, type : "bridge" },
      { x : 17, y : 6, type : "bridge" },
      { x : 18, y : 6, type : "bridge" },
      { x : 19, y : 6, type : "bridge" },
      { x : 19, y : 5, type : "bridge" },
      { x : 19, y : 4, type : "bridge" },
      { x : 20, y : 5, type : "bridge" },
      { x : 21, y : 5, type : "bridge" },
      { x : 21, y : 4, type : "bridge" },
      { x : 21, y : 3, type : "skull" },
      { x : 19, y : 0, type : "end" },
      { x : 19, y : 1, type : "bridge" },
      { x : 19, y : 2, type : "bridge" },
      { x : 19, y : 3, type : "bridge" },
      { x : 23, y : 0, type : "skull" },
      { x : 23, y : 1, type : "bridge" },
      { x : 23, y : 2, type : "bridge" },
      { x : 23, y : 3, type : "bridge" },
      { x : 23, y : 4, type : "bridge" },
      { x : 23, y : 5, type : "bridge" },
      { x : 23, y : 6, type : "bridge" },
      { x : 23, y : 7, type : "bridge" },
      { x : 23, y : 8, type : "bridge" },
      { x : 23, y : 9, type : "bridge" },
      { x : 23, y : 10, type : "bridge" },
      { x : 23, y : 11, type : "bridge" },
      { x : 23, y : 12, type : "bridge" },
      { x : 22, y : 12, type : "bridge" },
      { x : 21, y : 12, type : "bridge" },
      { x : 20, y : 12, type : "bridge" },
      { x : 19, y : 12, type : "bridge" },
      { x : 18, y : 12, type : "bridge" },
      { x : 17, y : 12, type : "bridge" },
      { x : 16, y : 12, type : "bridge" },
      { x : 15, y : 12, type : "bridge" },
      { x : 14, y : 12, type : "bridge" },
      { x : 13, y : 12, type : "bridge" },
      { x : 12, y : 12, type : "bridge" },
      { x : 11, y : 12, type : "bridge" },
      { x : 10, y : 12, type : "bridge" },
      { x : 9, y : 12, type : "bridge" },
      { x : 8, y : 12, type : "bridge" },
      { x : 7, y : 12, type : "bridge" },
      { x : 7, y : 11, type : "bridge" },
      { x : 8, y : 11, type : "bridge" },
      { x : 9, y : 11, type : "bridge" }
     ],

    /* LEVEL 4 */
    [
      { background : "earth" },
      { x : 18, y : 23, type : "start" },
      { x : 18, y : 22, type : "bridge" },
      { x : 19, y : 22, type : "bridge" },
      { x : 20, y : 22, type : "bridge" },
      { x : 21, y : 22, type : "bridge" },
      { x : 22, y : 22, type : "bridge" },
      { x : 23, y : 22, type : "bridge" },
      { x : 23, y : 21, type : "bridge" },
      { x : 23, y : 20, type : "bridge" },
      { x : 23, y : 19, type : "bridge" },
      { x : 23, y : 18, type : "bridge" },
      { x : 23, y : 17, type : "bridge" },
      { x : 23, y : 16, type : "bridge" },
      { x : 23, y : 15, type : "bridge" },
      { x : 23, y : 14, type : "bridge" },
      { x : 23, y : 13, type : "bridge" },
      { x : 23, y : 12, type : "bridge" },
      { x : 22, y : 22, type : "bridge" },
      { x : 21, y : 22, type : "bridge" },
      { x : 20, y : 22, type : "bridge" },
      { x : 19, y : 22, type : "bridge" },
      { x : 18, y : 22, type : "bridge" },
      { x : 17, y : 22, type : "bridge" },
      { x : 16, y : 22, type : "bridge" },
      { x : 15, y : 22, type : "bridge" },
      { x : 14, y : 22, type : "bridge" },
      { x : 13, y : 22, type : "bridge" },
      { x : 12, y : 22, type : "bridge" },
      { x : 11, y : 22, type : "bridge" },
      { x : 10, y : 22, type : "bridge" },
      { x : 9, y : 22, type : "bridge" },
      { x : 8, y : 22, type : "bridge" },
      { x : 8, y : 23, type : "bridge" },
      { x : 7, y : 23, type : "bridge" },
      { x : 6, y : 23, type : "bridge" },
      { x : 6, y : 22, type : "bridge" },
      { x : 5, y : 22, type : "bridge" },
      { x : 4, y : 22, type : "bridge" },
      { x : 4, y : 23, type : "deadend" },
      { x : 24, y : 12, type : "bridge" },
      { x : 25, y : 12, type : "bridge" },
      { x : 26, y : 12, type : "bridge" },
      { x : 27, y : 12, type : "bridge" },
      { x : 28, y : 12, type : "bridge" },
      { x : 29, y : 12, type : "bridge" },
      { x : 30, y : 12, type : "bridge" },
      { x : 31, y : 12, type : "end" }
    ]

  ];


} // End LevelMaps().
